version: "3"

services:

  database:
    restart: always
    image: postgres:latest
    user: postgres
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "ebisandb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rooter"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
      - ./database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - ebisan

  parser:
    build: ./parser
    depends_on:
      - database
    networks:
      - ebisan

  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "5000:8080"
    networks:
      - ebisan

  frontend:
    build: ./frontend
    depends_on:
      - database
    networks:
      - ebisan

volumes:
  postgres-data:
    driver: local

networks:
  ebisan:
